### ISSUE TITLE
*Error* eval: undefined function - CGstatusFormDiffCB

### ISSUE THREAD

**Issue by Ironil** [cdsgit/cdsgit#4]
Hello,

Upon selecting the button "Diff" from the CdsGit Status window, I get the error:
_Error_ eval: undefined function - CGstatusFormDiffCB

And nothing else happens

Also, how can I then diff between versions of a schematic?

Thank you, and nice work! Unfortunately I won't be able to help much, my lisp knowledge is 0, but I certainly plan on using Cdsgit extensively!

**Comment by cookacounty** [comment]
@Ironil thanks for the error report. Its great to hear you are using the tool!

For now I've made it so the Diff button just pops up the diff form without anything populated. Unfortunately for now you will have to manually populate the form:
- First export the last revision using the "export" feature from the schematic or library menu
- Open the diff form and manually populate the 2 schematic views.

I will work in the near future on making things more automated #5. Let me know if this does the trick for you.

Also, don't use the merge feature #6 since it gets screwed up with wire segments.
